module.exports = {
    url: 'ws://212.71.248.146:7012',
    symbols: [
        "BTCUSD",
        "BCHUSD",
        "ETHUSD",
        "LTCUSD",
        "XMRUSD",
        "DASHUSD",
        "ETCUSD",
        "RRTUSD",
        "RRTBTC",
        "ZECUSD",
        "ZECBTC",
        "XMRUSD",
        "XMRBTC",
        "DSHUSD",
        "DSHBTC",
        "BTCEUR",
        "BTCJPY",
        "XRPUSD",
        "XRPBTC",
        "IOTUSD",
        "IOTBTC",
        "IOTETH",
        "EOSUSD",
        "EOSBTC",
        "EOSETH",
        "SANUSD",
        "SANBTC",
        "SANETH",
        "OMGUSD",
        "OMGBTC",
        "OMGETH",
        "NEOUSD",
        "NEOBTC",
        "NEOETH",
        "ETPUSD",
        "ETPBTC",
        "ETPETH",
        "QTMUSD",
        "QTMBTC",
        "QTMETH",
        "AVTUSD",
        "AVTBTC",
        "AVTETH",
        "EDOUSD",
        "EDOBTC",
        "EDOETH",
        "BTGUSD",
        "BTGBTC",
        "DATUSD",
        "DATBTC",
        "DATETH",
        "QSHUSD",
        "QSHBTC",
        "QSHETH",
        "YYWUSD",
        "YYWBTC",
        "YYWETH",
        "GNTUSD",
        "GNTBTC",
        "GNTETH",
        "SNTUSD",
        "SNTBTC",
        "SNTETH",
        "IOTEUR",
        "BATUSD",
        "BATBTC",
        "BATETH",
        "MNAUSD",
        "MNABTC",
        "MNAETH",
        "FUNUSD",
        "FUNBTC",
        "FUNETH",
        "ZRXUSD",
        "ZRXBTC",
        "ZRXETH",
        "TNBUSD",
        "TNBBTC",
        "TNBETH",
        "SPKUSD",
        "SPKBTC",
        "SPKETH",
        "TRXUSD",
        "TRXBTC",
        "TRXETH",
        "RCNUSD",
        "RCNBTC",
        "RCNETH",
        "RLCUSD",
        "RLCBTC",
        "RLCETH",
        "AIDUSD",
        "AIDBTC",
        "AIDETH",
        "SNGUSD",
        "SNGBTC",
        "SNGETH",
        "REPUSD",
        "REPBTC",
        "REPETH",
        "ELFUSD",
        "ELFBTC",
        "ELFETH",
        "BTCGBP",
        "ETHEUR",
        "ETHJPY",
        "ETHGBP",
        "NEOEUR",
        "NEOJPY",
        "NEOGBP",
        "EOSEUR",
        "EOSJPY",
        "EOSGBP",
        "IOTJPY",
        "IOTGBP",
        "IOSUSD",
        "IOSBTC",
        "IOSETH",
        "AIOUSD",
        "AIOBTC",
        "AIOETH",
        "REQUSD",
        "REQBTC",
        "REQETH",
        "RDNUSD",
        "RDNBTC",
        "RDNETH",
        "LRCUSD",
        "LRCBTC",
        "LRCETH",
        "WAXUSD",
        "WAXBTC",
        "WAXETH",
        "DAIUSD",
        "DAIBTC",
        "DAIETH",
        "CFIUSD",
        "CFIBTC",
        "CFIETH",
        "AGIUSD",
        "AGIBTC",
        "AGIETH",
        "BFTUSD",
        "BFTBTC",
        "BFTETH",
        "MTNUSD",
        "MTNBTC",
        "MTNETH",
        "ODEUSD",
        "ODEBTC",
        "ODEETH",
        "ANTUSD",
        "ANTBTC",
        "ANTETH",
        "DTHUSD",
        "DTHBTC",
        "DTHETH",
        "MITUSD",
        "MITBTC",
        "MITETH",
        "STJUSD",
        "STJBTC",
        "STJETH",
        "XLMUSD",
        "XLMEUR",
        "XLMJPY",
        "XLMGBP",
        "XLMBTC",
        "XLMETH",
        "XVGUSD",
        "XVGEUR",
        "XVGJPY",
        "XVGGBP",
        "XVGBTC",
        "XVGETH",
        "BCIUSD",
        "BCIBTC",
        "MKRUSD",
        "MKRBTC",
        "MKRETH",
        "KNCUSD",
        "KNCBTC",
        "KNCETH",
        "POAUSD",
        "POABTC",
        "POAETH",
        "LYMUSD",
        "LYMBTC",
        "LYMETH",
        "UTKUSD",
        "UTKBTC",
        "UTKETH",
        "VEEUSD",
        "VEEBTC",
        "VEEETH",
        "DADUSD",
        "DADBTC",
        "DADETH",
        "ORSUSD",
        "ORSBTC",
        "ORSETH",
        "AUCUSD",
        "AUCBTC",
        "AUCETH",
        "POYUSD",
        "POYBTC",
        "POYETH",
        "FSNUSD",
        "FSNBTC",
        "FSNETH",
        "CBTUSD",
        "CBTBTC",
        "CBTETH",
        "ZCNUSD",
        "ZCNBTC",
        "ZCNETH",
        "SENUSD",
        "SENBTC",
        "SENETH",
        "NCAUSD",
        "NCABTC",
        "NCAETH",
        "CNDUSD",
        "CNDBTC",
        "CNDETH",
        "CTXUSD",
        "CTXBTC",
        "CTXETH",
        "PAIUSD",
        "PAIBTC",
        "SEEUSD",
        "SEEBTC",
        "SEEETH",
        "ESSUSD",
        "ESSBTC",
        "ESSETH",
        "ATMUSD",
        "ATMBTC",
        "ATMETH",
        "HOTUSD",
        "HOTBTC",
        "HOTETH",
        "DTAUSD",
        "DTABTC",
        "DTAETH",
        "IQXUSD",
        "IQXBTC",
        "IQXEOS",
        "WPRUSD",
        "WPRBTC",
        "WPRETH",
        "ZILUSD",
        "ZILBTC",
        "ZILETH",
        "BNTUSD",
        "BNTBTC",
        "BNTETH",
        "ABSUSD",
        "ABSETH",
        "XRAUSD",
        "XRAETH",
        "MANUSD",
        "MANETH",
        "BBNUSD",
        "BBNETH",
        "NIOUSD",
        "NIOETH",
        "DGXUSD",
        "DGXETH",
        "VETUSD",
        "VETBTC",
        "VETETH",
        "UTNUSD",
        "UTNETH",
        "TKNUSD",
        "TKNETH",
        "GOTUSD",
        "GOTEUR",
        "GOTETH",
        "XTZUSD",
        "XTZBTC",
        "CNNUSD",
        "CNNETH",
        "BOXUSD",
        "BOXETH",
        "TRXEUR",
        "TRXGBP",
        "TRXJPY",
        "MGOUSD",
        "MGOETH",
        "RTEUSD",
        "RTEETH",
        "YGGUSD",
        "YGGETH",
        "MLNUSD",
        "MLNETH",
        "WTCUSD",
        "WTCETH",
        "CSXUSD",
        "CSXETH",
        "OMNUSD",
        "OMNBTC",
        "INTUSD",
        "INTETH",
        "DRNUSD",
        "DRNETH",
        "PNKUSD",
        "PNKETH",
        "DGBUSD",
        "DGBBTC",
        "BSVUSD",
        "BSVBTC",
        "BABUSD",
        "BABBTC",
        "EURUSDv",
        "AUDCADv",
        "EURJPYv",
        "EURCHFv",
        "USDJPYv",
        "USDCADv",
        "XAUEURv",
        "XAGUSDv",
        "XAUUSDv",
        "CADJPYv",
        "SGDJPYv",
        "CHFJPYv",
        "CADCHFv",
        "AUDJPYv",
        "AUDCHFv",
        "GBPJPYv",
        "GBPCADv",
        "GBPCHFv",
        "GBPAUDv",
        "NZDJPYv",
        "NZDCADv",
        "AUDNZDv",
        "GBPNZDv",
        "EURCADv",
        "NZDCHFv",
        "EURAUDv",
        "EURGBPv",
        "EURNZDv",
        "EURNOKv",
        "EURSGDv",
        "EURSEKv",
        "EURHKDv",
        "EURTRYv",
        "EURPLNv",
        "EURDKKv",
        "USDCHFv",
        "GBPUSDv",
        "NZDUSDv",
        "XAGEURv",
        "USDNOKv",
        "USDSGDv",
        "USDSEKv",
        "USDHKDv",
        "USDTRYv",
        "USDPLNv",
        "USDDKKv",
        "USDRUBv",
        "AUDUSDv",
        "DASHUSD",
        "BCHUSD",
        "USDUAH",
        "USDCNY",
        "AUDUSDecn",
        "EURGBPecn",
        "EURUSDecn",
        "GBPUSDecn",
        "NZDUSDecn",
        "USDCADecn",
        "USDCHFecn",
        "USDJPYecn",
        "XAUUSDecn",
        "AUDJPY",
        "AUDUSD",
        "EURCHF",
        "EURGBP",
        "EURJPY",
        "EURUSD",
        "GBPCHF",
        "GBPJPY",
        "GBPUSD",
        "NZDUSD",
        "USDCAD",
        "USDCHF",
        "USDJPY",
        "AUDUSDbig",
        "EURGBPbig",
        "EURUSDbig",
        "GBPUSDbig",
        "NZDUSDbig",
        "USDCADbig",
        "USDCHFbig",
        "USDJPYbig",
        "AUS200v",
        "COPPERv",
        "FRA40v",
        "GER30v",
        "NATGASv",
        "UK100v",
        "UKOILv",
        "USA100v",
        "USA30v",
        "USA500v",
        "USOILv",
        "ADIDAS",
        "AIRBUS",
        "BMW",
        "CONG",
        "TOYOTA",
        "SONY",
        "AMAZON",
        "GOOGLE",
        "BOEING",
        "NETFLIX",
        "TESLA",
        "NVIDIA",
        "MCARD",
        "APPLE",
        "FACEBOOK",
        "IBM",
        "VISA",
        "FERRARI",
        "CHEVRON",
        "MSFT",
        "DISNEY",
        "WMART",
        "NIKE",
        "MCDON",
        "INTEL",
        "GM",
        "HPACK",
        "COCA",
        {
        	name: "BTCETC",
        	digits: 5,
        	left: "BTCUSD",
        	leftFlip: false,
        	right: "ETCUSD",
        	rightFlip: false
        },
        {
        	name: "ETHETC",
        	digits: 5,
        	left: "ETHUSD",
        	leftFlip: false,
        	right: "ETCUSD",
        	rightFlip: false
        },
        {
        	name: "BCHETC",
        	digits: 5,
        	left: "BCHUSD",
        	leftFlip: false,
        	right: "ETCUSD",
        	rightFlip: false
        },
        {
        	name: "LTCETC",
        	digits: 5,
        	left: "LTCUSD",
        	leftFlip: false,
        	right: "ETCUSD",
        	rightFlip: false
        },
        {
        	name: "XMRETC",
        	digits: 5,
        	left: "XMRUSD",
        	leftFlip: false,
        	right: "ETCUSD",
        	rightFlip: false
        },
        {
        	name: "DASHETC",
        	digits: 5,
        	left: "DASHUSD",
        	leftFlip: false,
        	right: "ETCUSD",
        	rightFlip: false
        },
        {
        	name: "BTCBCH",
        	digits: 5,
        	left: "BTCUSD",
        	leftFlip: false,
        	right: "BCHUSD",
        	rightFlip: false
        },
        {
        	name: "BTCETH",
        	digits: 5,
        	left: "BTCUSD",
        	leftFlip: false,
        	right: "ETHUSD",
        	rightFlip: false
        },
        {
        	name: "BTCLTC",
        	digits: 5,
        	left: "BTCUSD",
        	leftFlip: false,
        	right: "LTCUSD",
        	rightFlip: false
        },
        {
        	name: "BTCXMR",
        	digits: 5,
        	left: "BTCUSD",
        	leftFlip: false,
        	right: "XMRUSD",
        	rightFlip: false
        },
        {
        	name: "BTCDASH",
        	digits: 5,
        	left: "BTCUSD",
        	leftFlip: false,
        	right: "DASHUSD",
        	rightFlip: false
        },
        {
        	name: "BCHETH",
        	digits: 5,
        	left: "BCHUSD",
        	leftFlip: false,
        	right: "ETHUSD",
        	rightFlip: false
        },
        {
        	name: "BCHLTC",
        	digits: 5,
        	left: "BCHUSD",
        	leftFlip: false,
        	right: "LTCUSD",
        	rightFlip: false
        },
        {
        	name: "BCHXMR",
        	digits: 5,
        	left: "BCHUSD",
        	leftFlip: false,
        	right: "XMRUSD",
        	rightFlip: false
        },
        {
        	name: "BCHDASH",
        	digits: 5,
        	left: "BCHUSD",
        	leftFlip: false,
        	right: "DASHUSD",
        	rightFlip: false
        },
        {
        	name: "ETHLTC",
        	digits: 5,
        	left: "ETHUSD",
        	leftFlip: false,
        	right: "LTCUSD",
        	rightFlip: false
        },
        {
        	name: "ETHXMR",
        	digits: 5,
        	left: "ETHUSD",
        	leftFlip: false,
        	right: "XMRUSD",
        	rightFlip: false
        },
        {
        	name: "ETHDASH",
        	digits: 5,
        	left: "ETHUSD",
        	leftFlip: false,
        	right: "DASHUSD",
        	rightFlip: false
        },
        {
        	name: "LTCXMR",
        	digits: 5,
        	left: "LTCUSD",
        	leftFlip: false,
        	right: "XMRUSD",
        	rightFlip: false
        },
        {
        	name: "LTCDASH",
        	digits: 5,
        	left: "LTCUSD",
        	leftFlip: false,
        	right: "DASHUSD",
        	rightFlip: false
        },
        {
        	name: "XMRDASH",
        	digits: 5,
        	left: "XMRUSD",
        	leftFlip: false,
        	right: "DASHUSD",
        	rightFlip: false
        }
    ],
};
